### ISSUE TITLE
В консоли не работает кнопка Открыть папку с логами

### ISSUE THREAD

**Issue by Sn1fferx** [Seeroy/FrogLauncher2#6]
При нажатии на кнопку ничего не происходит

https://github.com/user-attachments/assets/b5def51e-ce5e-4fe8-8be5-93c8f8d24f02

**Comment by Sn1fferx** [comment]
[FL_debug-1726422176270-5915ad50-71ef-11ef-8af5-87be324c2891.zip](https://github.com/user-attachments/files/17006767/FL_debug-1726422176270-5915ad50-71ef-11ef-8af5-87be324c2891.zip)

**Comment by Seeroy** [comment]
Папка с логами не откроется, если её нет. Создаётся при первом запуске игры. В следующем обновлении добавлю создание папки при открытии
