### ISSUE TITLE
При установке обновления кнопка "Установить" с $

### ISSUE THREAD

**Issue by Sn1fferx** [Seeroy/FrogLauncher2#7]
![Снимок экрана 2024-09-18 093114](https://github.com/user-attachments/assets/f5c985ab-722b-49bf-9d3c-1bdb0a8a630b)
и ещё кнопка кнопка исходный код проекта переносит на старый репозиторий

**Comment by Seeroy** [comment]
Символ "$" на кнопке установки уже исправлен в последнем обновлении. Второй баг проверю, спасибо

**Comment by Seeroy** [comment]
Исправлено в [этом коммите](https://github.com/Seeroy/FrogLauncher2/commit/943e16e63c3f3a1e210b35e1a24cc4aa38c42c52), ждите обновление, спасибо
